#pragma once

#define DB_CONNECTION_FAIL 255
#define LOGIN_ERROR_NO_ERROR 0
#define LOGIN_ERROR_WRONG_USERNAME 1
#define LOGIN_ERROR_WRONG_PASSWORD 2


#define MIN_USERINFO_SIZE 8
#define MAX_USERINFO_SIZE 16
#define MAX_USERNAME_SIZE 16
#define MAX_PASSWORD_SIZE 16

enum class PacketType : unsigned char
{
	LOGIN_REQUEST,
	LOGIN_REPLY,
	LOGOUT,
	CREATE_ACCOUNT_REQUEST,
	CREATE_ACCOUNT_REPLY,
	ROOM_ENTER_REQUEST,
	ROOM_ENTER_REPLY,
	ROOM_EXIT_REQUEST,
	ROOM_EXIT_REPLY,
	ROOM_INFO_REQUEST,
	ROOM_INFO_REPLY, 
	CHAT,
	TEST
};